# Generated by Django 5.1.1 on 2024-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Popular', 'Popular'), ('Featured', 'Featured'), ('More Visited', 'More Visited'), ('Europe', 'Europe'), ('Asia', 'Asia')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reviews', models.TextField()),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
